version: '3'
services:

  nodejs:
    build:
      context: .
      dockerfile: ./docker/nodejs/Dockerfile
    container_name: "${DOCKER_PREFIX}-nodejs"
    user: "1000:1000"
    ports:
      - "3000:3000"
    volumes:
      - ./app:/var/www
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
